ElectricStore/ElectricStore/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ElectricStore.Data;
using ElectricStore.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace ElectricStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        private StoreContext _context;
        private List<Product> products;
        private SessionStateViewModel sessionModel;

        public ShoppingCartController(StoreContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            if(!string.IsNullOrEmpty(HttpContext.Session.GetString("CustomerFirstName")) &&
                !string.IsNullOrEmpty(HttpContext.Session.GetString("CustomerProducts")))
            {
                List<int> productsListId = JsonConvert.DeserializeObject<List<int>>(HttpContext.Session.GetString("CustomerProducts"));
                products = new List<Product>();

                foreach(var item in productsListId)
                {
                    var product = _context.Products.SingleOrDefault(p => p.Id == item);
                    products.Add(product);
                }
                sessionModel = new SessionStateViewModel();
                sessionModel.CustomerName = HttpContext.Session.GetString("CustomerFirstName");
                sessionModel.SelectedProducts = products;
                return View(sessionModel);
            }
            return View();
        }


        public IActionResult Chat()
        {
            return View();
        }
    }
}

ElectricStore/ElectricStore/Views/Shared/Components/NavbarMenu/MenuCategories.cshtml
@model IEnumerable<ElectricStore.Models.MenuCategory>

<li class="nav-item">
    <a class="nav-link" href="@Url.Action("Index", "Products")">
        Home<span class="sr-only">(current)</span>
    </a>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Electronics
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        @foreach(var item in Model)
        {
            <a class="dropdown-item" asp-action="GetByCategory" asp-controller="Products" asp-route-id="@item.Id">
                @Html.DisplayFor(modelItem => item.Name)
            </a>
        }
    </div>
</li>
<li class="nav-item">
    <a class="nav-link" href="@Url.Action("AddToShoppingList", "Products")">
        Add to Shopping List
    </a>
</li>
<li class="nav-item">
    <a class="nav-link" href="@Url.Action("Index", "ShoppingCart")">
        My Shopping Cart
    </a>
</li>
<li class="nav-item">
    <div class="display-cached-time">
         The content cached Since: @DateTime.Now
    </div>
</li>